name: testing

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node:
          - '12'
          - '14'
          - '16'
          - '18'
        sql:
          - 'mysql:5.6'
          - 'mysql:5.7'
          - 'mysql:8.0'
          - 'mariadb:10.2'
          - 'mariadb:10.3'
          - 'mariadb:10.4'
          - 'mariadb:10.5'
          - 'mariadb:10.6'
          - 'mariadb:10.7'
          - 'mariadb:10.8'
    name: Node ${{ matrix.node }}, MySQL/MariaDB ${{ matrix.sql }}
    services:
      mysql:
        image: ${{ matrix.sql }}
        env:
          MYSQL_DATABASE: mp_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: adminpass
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
        env:
          MYSQL_DATABASE: mp_test
          MYSQL_USER: admin
          MYSQL_PASS: adminpass
