name: testing

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node:
          - '14'
          - '16'
    name: Node ${{ matrix.node }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: mp_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: adminpass
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
